#!/usr/bin/env bash

array_is_empty() {
  if [[ "$(declare -p $1)" == "declare -a $1=([0]=\"\")" ]]; then
    return 0
  fi
  return 1
}

info() {
  printf '\e[33m%s\e[0m\n' "$*"
  # set -x
  if [[ "$debug" == true ]]; then
    export PS4="\n\033[1;33mRunning linter: \033[0m"
    set -x
  else
    trap "[[ \$BASH_COMMAND != trap\ * ]] && info \$BASH_COMMAND" DEBUG
  fi
}

latest_commit_only=false
debug=false
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --latest-commit)
      latest_commit_only=true
      ;;
    --debug)
      debug=true
      ;;
  esac
  shift
done

git config --global --add safe.directory /repo

# Python

if [[ "$latest_commit_only" == true ]]; then
  readarray -t files <<<"$(git diff-tree --no-commit-id --name-only -r HEAD)"
else
  readarray -t files <<<"$(git ls-files '*.py')"
fi

if ! array_is_empty files; then
  info 'Linting Python files'
  bandit --silent "${files[@]}"
  black --check --diff --quiet "${files[@]}"
  flake8 "${files[@]}"
  isort --check-only "${files[@]}"
  pydocstyle "${files[@]}"
  mypy --install-types --non-interactive "${files[@]}"
  vulture "${files[@]}"
  { trap - DEBUG; set +x; } 2>/dev/null
fi

# markdown
# flake8-markdown *.md
