---

plugins:
  remark-preset-lint-markdown-style-guide: ~

  remark-lint-checkbox-character-style: ~
  remark-lint-checkbox-content-indent: ~
  remark-lint-fenced-code-flag-case: ~
  remark-lint-final-newline: ~
  remark-lint-first-heading-level: ~
  remark-lint-heading-word-length: ~
  remark-lint-linebreak-style: ~
  remark-lint-list-item-bullet-indent: ~
  remark-lint-list-item-style: ~
  remark-lint-no-duplicate-defined-urls: ~
  remark-lint-no-duplicate-definitions: ~
  remark-lint-no-duplicate-headings-in-section: ~
  remark-lint-no-empty-url: ~
  remark-lint-no-heading-content-indent: ~
  remark-lint-no-heading-indent: ~
  remark-lint-no-heading-like-paragraph: ~
  remark-lint-no-html: ~
  remark-lint-no-missing-blank-lines: ~
  remark-lint-no-paragraph-content-indent: ~
  remark-lint-no-reference-like-url: ~
  remark-lint-no-tabs: ~
  remark-lint-no-undefined-references: ~
  remark-lint-no-unneeded-full-reference-image: ~
  remark-lint-no-unneeded-full-reference-link: ~
  remark-lint-no-unused-definitions: ~
  remark-lint-strikethrough-marker: ~

  remark-lint-maximum-line-length: 70
