---

dependency:
  name: galaxy
  requirements-file: requirements.txt
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint . molecule
  flake8
platforms:
  - name: ${MOLECULE_INSTANCE_NAME-molecule-test}
    image: ${MOLECULE_DOCKER_IMAGE-geerlingguy/docker-ubuntu1804-ansible:latest}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_native: true
      duplicate_dict_key: error
      any_unparsed_is_failed: true
      unparsed_is_failed: true
      any_errors_fatal: true
  playbooks:
    side_effect: side_effect.yml
verifier:
  name: ansible
