---

dependency:
  name: shell
  command: >
    bash -c "
    [[ -e '${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml' ]] &&
    ansible-galaxy install -r '${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml' ||
    :
    "
driver:
  name: ${CUSTOM_MOLECULE_DRIVER:-docker}
lint: |
  set -e
  yamllint -c "${PROJECT_DIR-.}/.yamllint" .
  ansible-lint -c "${PROJECT_DIR-.}/.ansible-lint" .
platforms:
  - name: ${CUSTOM_MOLECULE_INSTANCE_NAME:-molecule-test}
    image: ${CUSTOM_MOLECULE_CONTAINER_IMAGE:-geerlingguy/docker-ubuntu1804-ansible:latest}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      duplicate_dict_key: error
      any_unparsed_is_failed: true
      unparsed_is_failed: true
      any_errors_fatal: true
  playbooks:
    side_effect: side_effect.yml
verifier:
  name: ansible
