---

name: Lint

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      enabled:
        required: true
        type: boolean
      pr_mode:
        required: false
        default: true
        type: boolean
      base_ref:
        required: false
        default: ${{ github.base_ref }}
        type: string
      head_ref:
        required: false
        default: ${{ github.head_ref }}
        type: string
      debug:
        required: false
        default: false
        type: boolean
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch: ~

jobs:
  lint:
    if: ${{ inputs.enabled }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone with full history and checkout pull branch
        # The script that runs the linters may need to compare the base and head
        # refs to extract the changed files in the pull request. GitHub Actions
        # checkouts only the head ref. Here, the base ref will also be checked
        # out so that revisions like `master..pull-branch` are valid.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout pull target
        run: git branch ${{ inputs.base_ref }} --track origin/${{ inputs.base_ref }}

      - name: Run linters using docker image
        run: >-
          mkdir -p /tmp/upper /tmp/workdir;
          docker run
          --pull always -t --rm
          -e PR_MODE=${{ inputs.enabled }}
          -e DEBUG=${{ inputs.debug }}
          -e BASE_REF=${{ inputs.base_ref }}
          -e HEAD_REF=${{ inputs.head_ref }}
          --mount type=volume,dst=/repo,volume-driver=local,volume-opt=type=overlay,\"volume-opt=o=lowerdir=${PWD}/,upperdir=/tmp/upper,workdir=/tmp/workdir\",volume-opt=device=overlay
          nkakouros/linter-configs:latest
