---

name: Lint

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      enabled:
        required: true
        type: boolean
      debug:
        required: false
        default: false
        type: boolean
      override_repo:
        required: false
        type: string

      mypypath:
        required: false
        type: string
      ansible_collections_dirs:
        required: false
        type: string
    secrets:
      override_repo_token:
        required: false
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch: ~

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Clone with full history and checkout pull branch
        # The script that runs the linters may need to compare the base and head
        # refs to extract the changed files in the pull request. GitHub Actions
        # checkouts only the head ref. Here, the base ref will also be checked
        # out so that revisions like `master..pull-branch` are valid.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Checkout pull target
        if: github.event_name == 'pull_request'
        run: |
          git branch ${{ github.base_ref }} --track origin/${{ github.base_ref }}

      - name: Checkout override repo
        if: ${{ inputs.override_repo }}
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.override_repo }}
          path: .override-repo
          token: ${{ secrets.override_repo_token }}

      - name: Copy files from override repo
        if: ${{ inputs.override_repo }}
        run: cp -n .override-repo/* .

      - name: Run linters using docker image
        run: >-
          mkdir -p /tmp/upper /tmp/workdir;
          docker run
          --pull always -t --rm
          -e GITHUB_ACTION=${{ github.action }}
          -e PR_MODE=${{ github.event_name == 'pull_request' }}
          -e DEBUG=${{ inputs.debug }}
          -e BASE_REF=${{ github.base_ref }}
          -e HEAD_REF=${{ github.head_ref }}
          -e MYPYPATH=${{ inputs.mypypath }}
          -e ANSIBLE_COLLECTIONS_DIRS=${{ inputs.ansible_collections_dirs }}
          -v /var/run/docker.sock:/var/run/docker.sock
          --mount type=volume,dst=/repo,volume-driver=local,volume-opt=type=overlay,\"volume-opt=o=lowerdir=${PWD}/,upperdir=/tmp/upper,workdir=/tmp/workdir\",volume-opt=device=overlay
          nkakouros/linter-configs:latest
